### ISSUE TITLE
Forcing a minimum number of assignments possible?

### ISSUE THREAD

**Issue by reichardtj** [motrom/fastmurty#2]
Dear Michael, thanks a lot for releasing this code. I very much appreciate your work.

I've run across the following problem with the python interface:

```
cost_matrix = np.ones((10, 10), dtype=np.float64) * np.inf
np.fill_diagonal(cost_matrix, -10)
```
will yield results as expected and assign along the diagonal. However, with
```
cost_matrix = np.ones((10, 10), dtype=np.float64) * np.inf
np.fill_diagonal(cost_matrix, 10)
```
I get no assignments with cost 0, which arguably is a minimal solution. 

Is there a way to force `min(num_rows, num_cols)` assignments in each of  `nsolutions`?

I can of course shift my entries in the cost matrix below zero and get around this problem, but I'd like to know if there is the option.

Thanks!

**Comment by motrom** [comment]
I didn't add any option like that, sorry.
But you're right that shifting entries below 0 will achieve the same thing. You can see I did a hack like that in https://github.com/motrom/fastmurty/blob/master/example_2frame.py#L25

**Comment by reichardtj** [comment]
Thanks for the reply. I'll stick with the shift then.
