### ISSUE TITLE
Matching targets and measurement

### ISSUE THREAD

**Issue by iamlvm** [motrom/fastmurty#3]
Hi,

I have a matrix with _n_ (rows) targets and _m+2_ (columns) ( _m_ measurement, _(m+1)^th_ for missed targets, _(m+2)^th_ for false targets.. In each hypothesis, I need a match between targets and measurement. For example, n=21, m=64, each hypothesis should **exactly return an array (21 dim)** like this `[0, 1, 45, 2, 3, 5, 6, 8, 9, 12, 11, 10, 13, 7, 14, 16, 15, 18, 17, 19, 63]`. It means that, target `#0` is matched measurement `#0`, target `#2` <=> measurement `#45`, target `#20` <=> measurement `#19`, target `#21` <=> measurement `63`. You can run the following [murty implementation](https://github.com/phquentin/lmb_tracker/blob/master/lmb/murty.py) with an example [matrix](https://github.com/motrom/fastmurty/files/6321656/matrix.txt).

I have tried to run your code with the above example matrix, but each hypothesis has _**mostly unmatched**_ between targets and measurement. (If we have a lower number of matches, we will have a lower matching cost). How can I get the result shown in the above example? 

Thank you

**Comment by motrom** [comment]
The likely reason is that, in this code, leaving a target/measurement unmatched is considered to have association cost 0. That means that only measurement/target pairs with negative costs (better than unmatched) have any chance of being matched.
I now see that this is not explicitly stated anywhere... my bad. But you can look at the example use files, they all use negative matrices.
In your case, try subtracting the maximum cost in your matrix from all elements.

**Comment by iamlvm** [comment]
use negative matrices, subtracting the maximum cost in a cost matrix from all elements
